import { useEffect, useMemo, useState } from "react";

import {
  History,
  RefreshCw,
  Search,
  ShieldAlert,
  MapPin,
  Clock3,
  Gauge,
  ChevronDown,
  ChevronUp,
  AlertTriangle,
  Database,
} from "lucide-react";

import { getPredictionHistory } from "../services/api";


function PredictionHistory() {

  const [records, setRecords] = useState([]);

  const [loading, setLoading] = useState(true);

  const [refreshing, setRefreshing] = useState(false);

  const [error, setError] = useState(null);

  const [search, setSearch] = useState("");

  const [riskFilter, setRiskFilter] =
    useState("ALL");

  const [expandedId, setExpandedId] =
    useState(null);


  async function loadHistory(showRefresh = false) {

    try {

      if (showRefresh) {
        setRefreshing(true);
      } else {
        setLoading(true);
      }

      setError(null);

      const data =
        await getPredictionHistory();

      /*
       * Backend returns:
       *
       * {
       *   count: number,
       *   records: [...]
       * }
       */

      setRecords(
        Array.isArray(data?.records)
          ? data.records
          : []
      );

    } catch (err) {

      console.error(
        "Prediction history error:",
        err
      );

      setError(
        err?.response?.data?.detail ||
        err?.message ||
        "Unable to load prediction history."
      );

    } finally {

      setLoading(false);
      setRefreshing(false);

    }
  }


  useEffect(() => {
    loadHistory();
  }, []);


  const filteredRecords =
    useMemo(() => {

      return records.filter(
        (record) => {

          const risk =
            record?.prediction?.risk_level ||
            record?.risk_level ||
            "";

          const latitude =
            record?.location?.latitude ??
            record?.latitude ??
            "";

          const longitude =
            record?.location?.longitude ??
            record?.longitude ??
            "";

          const searchText =
            `${risk} ${latitude} ${longitude} ${record?.id ?? ""}`
              .toLowerCase();

          const matchesSearch =
            searchText.includes(
              search.toLowerCase()
            );

          const matchesRisk =
            riskFilter === "ALL" ||
            risk === riskFilter;

          return (
            matchesSearch &&
            matchesRisk
          );
        }
      );

    }, [records, search, riskFilter]);


  function getRiskColor(risk) {

    if (risk === "HIGH_RISK") {
      return "text-red-400";
    }

    if (risk === "MEDIUM_RISK") {
      return "text-amber-400";
    }

    return "text-emerald-400";
  }


  function getRiskBackground(risk) {

    if (risk === "HIGH_RISK") {
      return "border-red-400/20 bg-red-400/5";
    }

    if (risk === "MEDIUM_RISK") {
      return "border-amber-400/20 bg-amber-400/5";
    }

    return "border-emerald-400/20 bg-emerald-400/5";
  }


  function formatRisk(risk) {

    return String(risk || "")
      .replace("_RISK", "")
      .replace("_", " ");
  }


  function formatDate(timestamp) {

    if (!timestamp) {
      return "Unknown";
    }

    try {

      return new Date(
        timestamp
      ).toLocaleString();

    } catch {

      return timestamp;

    }
  }


  function getLocation(record) {

    const latitude =
      record?.location?.latitude ??
      record?.latitude;

    const longitude =
      record?.location?.longitude ??
      record?.longitude;

    if (
      latitude === undefined ||
      longitude === undefined
    ) {
      return "Unknown location";
    }

    return `${Number(latitude).toFixed(4)}, ${Number(longitude).toFixed(4)}`;
  }


  return (
    <div className="space-y-6">

      {/* =====================================
          HEADER
      ===================================== */}

      <div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end">

        <div>

          <div className="flex items-center gap-2">

            <span className="h-2 w-2 rounded-full bg-cyan-400" />

            <span className="text-xs uppercase tracking-[0.2em] text-cyan-400">
              Database intelligence
            </span>

          </div>


          <h1 className="mt-3 text-3xl font-semibold text-white">
            Prediction History
          </h1>


          <p className="mt-2 text-sm text-slate-500">
            Review predictions generated by VIGIL and
            stored in PostgreSQL.
          </p>

        </div>


        <button
          onClick={() => loadHistory(true)}
          disabled={refreshing}
          className="flex items-center justify-center gap-2 rounded-xl border border-white/10 bg-white/[0.03] px-4 py-2.5 text-sm text-slate-300 transition hover:border-cyan-400/20 hover:text-white disabled:opacity-50"
        >

          <RefreshCw
            className={`h-4 w-4 ${
              refreshing
                ? "animate-spin"
                : ""
            }`}
          />

          Refresh

        </button>

      </div>


      {/* =====================================
          DATABASE SUMMARY
      ===================================== */}

      <div className="grid gap-4 md:grid-cols-3">

        <SummaryCard
          icon={
            <Database className="h-5 w-5" />
          }
          label="Total predictions"
          value={records.length}
        />


        <SummaryCard
          icon={
            <ShieldAlert className="h-5 w-5" />
          }
          label="Visible records"
          value={filteredRecords.length}
        />


        <SummaryCard
          icon={
            <History className="h-5 w-5" />
          }
          label="Data source"
          value="PostgreSQL"
        />

      </div>


      {/* =====================================
          FILTERS
      ===================================== */}

      <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-4">

        <div className="flex flex-col gap-3 lg:flex-row">

          {/* Search */}

          <div className="relative flex-1">

            <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-600" />

            <input
              value={search}
              onChange={(event) =>
                setSearch(
                  event.target.value
                )
              }
              placeholder="Search by risk, coordinates or prediction ID..."
              className="w-full rounded-xl border border-white/10 bg-[#07111f] py-3 pl-10 pr-4 text-sm text-white outline-none placeholder:text-slate-600 focus:border-cyan-400/30"
            />

          </div>


          {/* Risk filters */}

          <div className="flex gap-2 overflow-x-auto">

            {[
              "ALL",
              "LOW_RISK",
              "MEDIUM_RISK",
              "HIGH_RISK",
            ].map((filter) => {

              const active =
                riskFilter === filter;

              return (

                <button
                  key={filter}
                  onClick={() =>
                    setRiskFilter(filter)
                  }
                  className={`whitespace-nowrap rounded-xl px-4 py-2.5 text-xs font-medium transition ${
                    active
                      ? "bg-cyan-400 text-[#07111f]"
                      : "border border-white/10 bg-white/[0.02] text-slate-500 hover:text-white"
                  }`}
                >
                  {filter === "ALL"
                    ? "All"
                    : formatRisk(filter)}
                </button>

              );

            })}

          </div>

        </div>

      </div>


      {/* =====================================
          ERROR
      ===================================== */}

      {error && (

        <div className="rounded-2xl border border-red-400/20 bg-red-400/5 p-5">

          <div className="flex gap-3">

            <AlertTriangle className="h-5 w-5 text-red-400" />

            <div>

              <p className="font-medium text-red-300">
                Unable to load history
              </p>

              <p className="mt-1 text-sm text-slate-500">
                {error}
              </p>

            </div>

          </div>

        </div>

      )}


      {/* =====================================
          LOADING
      ===================================== */}

      {loading && (

        <div className="rounded-3xl border border-white/10 bg-white/[0.025] p-12 text-center">

          <RefreshCw className="mx-auto h-7 w-7 animate-spin text-cyan-400" />

          <p className="mt-4 text-sm text-slate-500">
            Loading prediction history...
          </p>

        </div>

      )}


      {/* =====================================
          EMPTY
      ===================================== */}

      {!loading &&
        !error &&
        filteredRecords.length === 0 && (

          <div className="rounded-3xl border border-white/10 bg-white/[0.025] p-12 text-center">

            <History className="mx-auto h-8 w-8 text-slate-600" />

            <h2 className="mt-4 text-lg font-semibold text-white">
              No predictions found
            </h2>

            <p className="mt-2 text-sm text-slate-500">
              Try changing the search or risk filter.
            </p>

          </div>

        )}


      {/* =====================================
          RECORDS
      ===================================== */}

      {!loading &&
        filteredRecords.length > 0 && (

          <div className="space-y-3">

            {filteredRecords.map(
              (record) => {

                const prediction =
                  record.prediction ||
                  record;

                const risk =
                  prediction.risk_level;

                const confidence =
                  prediction.confidence_percent;

                const sensitivity =
                  prediction.recommended_sensitivity;

                const expanded =
                  expandedId === record.id;


                return (

                  <div
                    key={record.id}
                    className="overflow-hidden rounded-2xl border border-white/10 bg-white/[0.025]"
                  >

                    {/* Main row */}

                    <button
                      onClick={() =>
                        setExpandedId(
                          expanded
                            ? null
                            : record.id
                        )
                      }
                      className="w-full p-5 text-left transition hover:bg-white/[0.02]"
                    >

                      <div className="grid items-center gap-5 lg:grid-cols-[1.4fr_1fr_1fr_1fr_auto]">

                        {/* Risk */}

                        <div className="flex items-center gap-3">

                          <div
                            className={`rounded-xl border p-2.5 ${getRiskBackground(risk)}`}
                          >

                            <ShieldAlert
                              className={`h-5 w-5 ${getRiskColor(risk)}`}
                            />

                          </div>


                          <div>

                            <p className={`font-semibold ${getRiskColor(risk)}`}>
                              {formatRisk(risk)}
                            </p>

                            <p className="mt-1 text-xs text-slate-600">
                              Prediction #{record.id}
                            </p>

                          </div>

                        </div>


                        {/* Location */}

                        <div>

                          <p className="flex items-center gap-2 text-xs uppercase tracking-wider text-slate-600">
                            <MapPin className="h-3.5 w-3.5" />
                            Location
                          </p>

                          <p className="mt-1 text-sm text-slate-300">
                            {getLocation(record)}
                          </p>

                        </div>


                        {/* Confidence */}

                        <div>

                          <p className="text-xs uppercase tracking-wider text-slate-600">
                            Confidence
                          </p>

                          <p className="mt-1 text-sm font-semibold text-white">
                            {confidence}%
                          </p>

                        </div>


                        {/* Sensitivity */}

                        <div>

                          <p className="flex items-center gap-2 text-xs uppercase tracking-wider text-slate-600">
                            <Gauge className="h-3.5 w-3.5" />
                            Sensitivity
                          </p>

                          <p className="mt-1 text-sm font-semibold text-cyan-300">
                            {sensitivity}
                          </p>

                        </div>


                        {/* Expand */}

                        <div className="flex justify-end">

                          {expanded ? (
                            <ChevronUp className="h-5 w-5 text-slate-500" />
                          ) : (
                            <ChevronDown className="h-5 w-5 text-slate-500" />
                          )}

                        </div>

                      </div>


                      {/* Timestamp */}

                      <div className="mt-4 flex items-center gap-2 text-xs text-slate-600">

                        <Clock3 className="h-3.5 w-3.5" />

                        {formatDate(
                          record.created_at
                        )}

                      </div>

                    </button>


                    {/* =================================
                        EXPANDED DETAILS
                    ================================= */}

                    {expanded && (

                      <div className="border-t border-white/10 bg-black/10 p-5">

                        <div className="grid gap-5 lg:grid-cols-2">

                          {/* Weather */}

                          <div>

                            <p className="text-xs uppercase tracking-[0.15em] text-slate-600">
                              Weather conditions
                            </p>


                            <div className="mt-3 grid grid-cols-2 gap-2">

                              <WeatherValue
                                label="Wind"
                                value={
                                  record.weather?.wind_speed_kmh ??
                                  record.wind_speed_kmh
                                }
                                unit="km/h"
                              />

                              <WeatherValue
                                label="Rainfall"
                                value={
                                  record.weather?.rainfall_mm ??
                                  record.rainfall_mm
                                }
                                unit="mm"
                              />

                              <WeatherValue
                                label="Temperature"
                                value={
                                  record.weather?.temperature_c ??
                                  record.temperature_c
                                }
                                unit="°C"
                              />

                              <WeatherValue
                                label="Humidity"
                                value={
                                  record.weather?.humidity_percent ??
                                  record.humidity_percent
                                }
                                unit="%"
                              />

                            </div>

                          </div>


                          {/* Explanation */}

                          <div>

                            <p className="text-xs uppercase tracking-[0.15em] text-slate-600">
                              Decision explanation
                            </p>


                            <p className="mt-3 text-sm leading-6 text-slate-400">
                              {record.explanation?.summary ||
                                record.explanation_summary ||
                                "No explanation available."}
                            </p>


                            <div className="mt-3 space-y-2">

                              {(
                                record.explanation?.factors ||
                                []
                              ).map(
                                (factor, index) => (

                                  <div
                                    key={index}
                                    className="rounded-lg border border-white/5 bg-white/[0.02] px-3 py-2 text-xs leading-5 text-slate-500"
                                  >
                                    {factor}
                                  </div>

                                )
                              )}

                            </div>

                          </div>

                        </div>

                      </div>

                    )}

                  </div>

                );

              }
            )}

          </div>

        )}

    </div>
  );
}


// ============================================
// SUMMARY CARD
// ============================================

function SummaryCard({
  icon,
  label,
  value,
}) {

  return (

    <div className="rounded-2xl border border-white/10 bg-white/[0.025] p-5">

      <div className="flex items-center justify-between">

        <p className="text-xs uppercase tracking-[0.15em] text-slate-600">
          {label}
        </p>

        <span className="text-cyan-400">
          {icon}
        </span>

      </div>


      <p className="mt-4 text-2xl font-semibold text-white">
        {value}
      </p>

    </div>

  );
}


// ============================================
// WEATHER VALUE
// ============================================

function WeatherValue({
  label,
  value,
  unit,
}) {

  return (

    <div className="rounded-xl border border-white/5 bg-white/[0.02] p-3">

      <p className="text-[10px] uppercase tracking-wider text-slate-600">
        {label}
      </p>

      <p className="mt-1 text-sm font-medium text-slate-300">

        {value ?? "—"}

        {unit && (
          <span className="ml-1 text-xs text-slate-600">
            {unit}
          </span>
        )}

      </p>

    </div>

  );
}


export default PredictionHistory;